"""
rules/rule_engine.py
====================
Core rule engine for Carbonaire.

Defines:
  - Severity enum (CRITICAL, HIGH, MEDIUM, LOW, INFO)
  - Finding dataclass (one per triggered rule)
  - RuleEngine: loads all scope rules and fires them

HOW IT WORKS:
  1. RuleEngine collects all rules from scope1_rules, scope2_rules, scope3_rules.
  2. For each rule function, it calls rule(result, data).
  3. Each rule returns a list of Finding objects (empty if rule didn't trigger).
  4. All findings are aggregated and returned sorted by severity.

HOW TO EXTEND:
  - To add a new rule file (e.g. for a new scope or category):
    Import it here and add to ALL_RULE_SETS.
"""

from dataclasses import dataclass
from enum import IntEnum
from typing import List, Callable


class Severity(IntEnum):
    CRITICAL = 5
    HIGH     = 4
    MEDIUM   = 3
    LOW      = 2
    INFO     = 1

    def label(self) -> str:
        return self.name

    def emoji(self) -> str:
        # ASCII-safe symbols for Windows consoles
        return {
            5: "[CRIT]",
            4: "[HIGH]",
            3: "[MED ]",
            2: "[LOW ]",
            1: "[INFO]",
        }[self.value]


@dataclass
class Finding:
    """
    A single insight or recommendation generated by a rule.
    """
    severity:       Severity
    scope:          str        # "Scope 1" / "Scope 2" / "Scope 3" / "Overall"
    category:       str        # e.g. "Diesel Generator", "Renewable Energy"
    message:        str        # What the issue/observation is
    recommendation: str        # What to do about it


class RuleEngine:
    """
    Loads all rules and evaluates them against calculation results.
    """

    def __init__(self):
        # Import rule sets — add new rule modules here
        from rules.scope1_rules import SCOPE1_RULES
        from rules.scope2_rules import SCOPE2_RULES
        from rules.scope3_rules import SCOPE3_RULES
        from rules.overall_rules import OVERALL_RULES

        self.all_rules: List[Callable] = (
            SCOPE1_RULES + SCOPE2_RULES + SCOPE3_RULES + OVERALL_RULES
        )

    def evaluate(self, result: dict, data) -> List[Finding]:
        """
        Run all rules against the calculation result.

        Parameters:
          result: output of master_calculator.run_calculation()
          data:   the original CarbonInputData object

        Returns:
          List of Finding objects, sorted by severity (highest first).
        """
        all_findings: List[Finding] = []

        for rule_fn in self.all_rules:
            try:
                findings = rule_fn(result, data)
                all_findings.extend(findings)
            except Exception as e:
                # A bad rule should not crash the whole engine
                all_findings.append(Finding(
                    severity=Severity.INFO,
                    scope="System",
                    category="Rule Error",
                    message=f"Rule '{rule_fn.__name__}' failed: {e}",
                    recommendation="Check rule logic.",
                ))

        # Sort: highest severity first, then by scope
        all_findings.sort(key=lambda f: (-f.severity.value, f.scope, f.category))
        return all_findings


def summarise_findings(findings: List[Finding]) -> dict:
    """
    Returns a count summary of findings by severity.
    {
        "CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4,
        "total": 10
    }
    """
    counts = {s.name: 0 for s in Severity}
    for f in findings:
        counts[f.severity.name] += 1
    counts["total"] = len(findings)
    return counts
